### ISSUE TITLE
`make html` not working in nix development environment

### ISSUE THREAD

**Issue by sloschert** [arbeitszeit/arbeitszeitapp#941]
**Description:**

When working in nix dev shell (activated by `nix develop`) I cannot run the `make html` command to generate the documentation as described in the README (https://github.com/arbeitszeit/arbeitszeitapp?tab=readme-ov-file#documentation)

**Details:**

Output:

```bash
❯ make html
Traceback (most recent call last):
  File "/nix/store/1l5mygrbwwcr9d15wh0bd593pzdbng68-python3.11-sphinx-7.2.6/bin/.sphinx-build-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/1l5mygrbwwcr9d15wh0bd593pzdbng68-python3.11-sphinx-7.2.6/lib/python3.11/site-packages/sphinx/cmd/build.py", line 326, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/nix/store/asiphbpiy2gmidfm3xbwcikayhs66289-python3-3.11.7/lib/python3.11/locale.py", line 627, in setlocale
    return _setlocale(category, locale)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
locale.Error: unsupported locale setting
make: *** [Makefile:20: html] Error 1
```

Outout of `locale` command (also in nix develop shell):

```bash
❯ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=de_DE.UTF-8
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
```

When I am NOT in the nix environment, I can run the command and generate the docs. 

I am not sure if this is a problem of my local setup. Can you reproduce it?

**Comment by petsch0** [comment]
I was not able to reproduce this locally, make html worked just fine using nix develop shell. However, #943 breaks dev setup on aarch64 mac. output when entering repo root folder:
```
direnv: loading ~/arbeitszeitapp/.envrc
direnv: using flake --extra-experimental-features nix-command --extra-experimental-features flakes
evaluating derivation 'git+file:///Users/I539136/arbeitszeitapp#devShells.aarch64-darwin.default'direnv: ([/opt/homebrew/bin/direnv export zsh]) is taking a while to execute. Use CTRL-C to give up.
error:
       … while calling the 'derivationStrict' builtin
         at <nix/derivation-internal.nix>:9:12:
            8|
            9|   strict = derivationStrict drvAttrs;
             |            ^
           10|

       … while evaluating derivation 'nix-shell'
         whose name attribute is located at /nix/store/y7k6gpjwwspbpwvw3vax3xc3y53qg0rj-source/pkgs/stdenv/generic/make-derivation.nix:352:7

       … while evaluating attribute 'LOCALE_ARCHIVE' of derivation 'nix-shell'
         at /nix/store/0lfqzssmsxwgsrjfd5m28c7b5gwdjmjw-source/nix/devShell.nix:19:3:
           18|   inputsFrom = [ python3.pkgs.arbeitszeitapp ];
           19|   LOCALE_ARCHIVE = "${glibcLocales}/lib/locale/locale-archive";
             |   ^
           20| }

       error: cannot coerce null to a string: null
direnv: export +ARBEITSZEITAPP_CONFIGURATION_PATH +ARBEITSZEITAPP_TEST_DB +FLASK_APP +FLASK_DEBUG
```
I guess this means that I do not have LOCALE_ARCHIVE set? Or rather that I do no have this glibcLocales package installed? I tried manually via nix-env -iA nixpkgs.glibcLocales but it gives me
`error: expression does not evaluate to a derivation (or a set or list of those)`
also  nix build nixpkgs#glibcLocales outputs
`error: flake output attribute 'legacyPackages.aarch64-darwin.glibcLocales' is not a derivation or path`
maybe you have an idea how to fix this cross os and aarch?
